- name: Check if Helm binary exists
  ansible.builtin.stat:
    path: "/usr/local/bin/helm"
  register: helm_binary_check

- name: Ensure Helm is installed
  when: not helm_binary_check.stat.exists
  block:
    - name: Download the Helm installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: "0700"

    - name: Install Helm
      ansible.builtin.shell: /tmp/get_helm.sh
      args:
        executable: /bin/bash
      changed_when: false

    - name: Remove the Helm installation script
      ansible.builtin.file:
        path: /tmp/get_helm.sh
        state: absent

