site_name: Dotfiles
docs_dir: docs
repo_url: https://github.com/HYP3R00T/.dotfiles
repo_name: HYP3R00T/.dotfiles
theme:
  icon:
    logo: octicons/terminal-24
    menu: material/dots-grid
    search: octicons/search-24
  name: "material"
  palette:
    - scheme: Dark_Blue # Palette toggle for dark mode
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Prepare for Flashbang!
    - scheme: Light_Blue # Palette toggle for light mode
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Join the dark side. We have cookies.
  font:
    text: Inter
    code: Source Code Pro
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.prune
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - content.code.copy
    - search.share
    - search.suggest
plugins:
  - search
  # - roamlinks
  # - callouts
  - termynal:
      title: shell
      buttons: windows
      prompt_literal_start:
        - ">"
  - tags
  - open-in-new-tab
markdown_extensions:
  - footnotes
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HYP3R00T
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rajesh-kumar-das/
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@hyp3r00t
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/HYP3R00T
  status:
    new: Recently added
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2025 hyperoot.dev

nav:
  - Home: index.md
  - Learn:
      - learn/index.md
      - learn/laying-the-groundwork.md
      - learn/the-config-whisperer.md
      - learn/mapping-the-inventory.md
