- name: Ensure required dependencies are installed
  ansible.builtin.package:
    name: git
    state: present
  become: true

- name: Clone fzf repository
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ ansible_env.HOME }}/.fzf"
    depth: 1

- name: Run fzf install script
  ansible.builtin.command: "{{ ansible_env.HOME }}/.fzf/install --all"

- name: Add fzf configuration to .zshrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      source <(fzf --zsh)
      [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
    marker: "# {mark} fzf configuration"
    insertafter: "# Tool configurations"
    prepend_newline: true
    append_newline: true