- name: Ensure required dependencies are installed
  ansible.builtin.package:
    name: curl
    state: present
  become: true

- name: Install Starship
  ansible.builtin.shell:
    cmd: |
      curl -sS https://starship.rs/install.sh | sh -s -- -y
    creates: /usr/local/bin/starship
  become: true

- name: Verify Starship installation
  ansible.builtin.command:
    cmd: /usr/local/bin/starship --version
  register: starship_version
  changed_when: false

- name: Create Starship configuration directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'

- name: Copy Starship configuration file
  ansible.builtin.copy:
    src: files/starship.toml
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'

- name: Add Starship configuration to .zshrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      # Initiate Starship prompt
      eval "$(starship init zsh)"
    marker: "# {mark} Starship configuration"
    prepend_newline: true
  when: "'starship' in starship_version.stdout"